// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltipykptfpyxremksjgo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0aXB5a3B0ZnB5eHJlbWtzamdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NzEzNjMsImV4cCI6MjA2NTE0NzM2M30.tcxZVSvdTs7vvAyKXnW5a4PlTJsH0nTIT1dprB4KVWo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);